// <auto-generated />
namespace WTAdvent.Core.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class questions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(questions));
        
        string IMigrationMetadata.Id
        {
            get { return "201410171522544_questions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
