// <auto-generated />
namespace WTAdvent.Core.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addcorrecttranslationtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcorrecttranslationtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201411171010043_add-correct-translation-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
